# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        HoalBundle\Entity\Users:
            algorithm: bcrypt
            
    providers:
        our_db_provider:
            entity:
                class: HoalBundle:Users
                property: username

    firewalls:
        main:
#            pattern:   ^/login$
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        
        secured_area:
            pattern:    ^/
            form_login: ~
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/logged, roles: ROLE_ADMIN }
